### ISSUE TITLE
Nondeterministic "no longer in majority" exception when group is leaving 

### ISSUE THREAD

**Issue by xinzheyang** [Derecho-Project/derecho#129]
when group is leaving, `derecho_exception("Potential partitioning event: this node is no longer in the majority and must shut down!")` in `view_manager.cpp` is thrown nondeterministically.

This can be reproduced by running `derecho/src/applications/tests/performance_tests/bandwidth_test.cpp` using the config in [scripts/travis-ci/](https://github.com/Derecho-Project/derecho/tree/master/scripts/travis-ci) with 2-node setup. 
The above problem occurs with some chance.

Possible reason is that the states `gmsSST.rip` and `gmsSST.suspected` at the point of "not in majority" checking, is not what is intended in `ViewManager::leave()`.

**Comment by xinzheyang** [comment]
possibly duplicate with #84 , which was marked closed in commit https://github.com/Derecho-Project/derecho/commit/d2726d450f9a864c686f0c003f501f15f7863e21 and https://github.com/Derecho-Project/derecho/commit/e7e828fcc9598c998b4b3a5ca46e3f756b533d45

**Comment by KenBirman** [comment]
We also have an issue about not throwing this exception when a group of size 2 drops to size 1, and more broadly, making the threshold for enabling the partition-check flexible so that people can disable it entirely (like for a size 2 group), or specify a size at which it should start to kick in and disable it below that size.

**Comment by songweijia** [comment]
This is solved by commit d26f68087ac3818f289206117ba210ed098b9b40

**Comment by songweijia** [comment]
This is solved by commit d26f68087ac3818f289206117ba210ed098b9b40
