### ISSUE TITLE
Unexpected "Potential partitioning event" exception on node joining

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#132]
In a busy setup where messages are sending frequently, a joining node may trigger an unexpected exception on all non-leader nodes:
```
terminate called after throwing an instance of 'derecho::derecho_exception'
  what():  Potential partitioning event: this node is no longer in the majority and must shut down! Derecho version: 0.9.1+102
```
It seems to me that all nodes incorrectly suspected other nodes... This may be related to issue #126 and #92.

**Comment by KenBirman** [comment]
Shouldn't this be closed by now?

**Comment by songweijia** [comment]
I didn't see this in v2.0.
