### ISSUE TITLE
Multiple subgroups of the same type

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#137]
Derecho currently does not support multiple subgroups with the same type. For the Java wrapper API, we need this since different Java subgroup types map to the same C++ type, which routes `ordere_send` calls to Java side for dispatching based on `subgroup_index`.

However, there are a couple of designs in derecho prevent us from doing this:
1. `derecho::Group` class does not support duplicated `ReplicatedTypes` in its variadic template definition:
```
class Group : public virtual _Group, public GroupProjection<ReplicatedTypes>... {
};
```
2. `subgroup_allocation_map_t` in `SubgroupInfo`, as a map from subgroup type to its shard layout, does not support a same type for different subgroups.

**Comment by sagarjha** [comment]
Derecho has always supported multiple subgroups of the same type. I am surprised you missed this.

1. `derecho::Group` does not need to have the `ReplicatedTypes` duplicated. If multiple subgroups of the same type are desired, you still need to include the type name only once in the group definition.

2. `subgroup_allocation_map_t` in `SubgroupInfo` also stores subgroup data grouped by type. `subgroup_allocation_map_t` is a typedef for `std::map<std::type_index, subgroup_shard_layout_t>`. `subgroup_shard_layout_t` is not just the shard layout. It is a `std::vector<std::vector<SubView>>`. The outer vector is for the different subgroups. For each subgroup, the inner vector lists the subviews for every shard.

**Comment by songweijia** [comment]
Thanks for clarifying this. I did have a strong impression that multiple subgroups for a same type was considered because in the persistent code. Was feeling wired ...I probably need to stop for a moment.
