### ISSUE TITLE
Install scripts are dangerous

### ISSUE THREAD

**Issue by mpmilano** [Derecho-Project/derecho#139]
Looks like the install scripts feature cloning a repo straight into the current working directory, `cd`ing into it, ` cd ..`, and then an `rm -rf`.  There are a lot of ways this could fail, most of them involving a directory with the same target name as the `rm -rf ` existing.  This should be patched.

**Comment by songweijia** [comment]
I added `set -eu` in the scripts so that they will stop as soon as they fail for whatever reason. Or, we can just remove the `rm -rf` commands. What do you guys think?

**Comment by KenBirman** [comment]
I think just asking if they want us to remove the files might be adequate.  “Cleanup by executing rm -rf Derecho-build? [y/n]”

On Sep 30, 2019, at 8:15 PM, Weijia Song <notifications@github.com<mailto:notifications@github.com>> wrote:


I added set -eu in the scripts so that they will stop as soon as they fail for whatever reason. Or, we can just remove the rm -rf commands. What do you guys think?

**Comment by mpmilano** [comment]
What I think the new frontmatter for these scripts should be: 

```bash
set -eu
initial_dir=`pwd`
tmp_dir=`mktemp`
cd $tmp_dir
#existing script goes here ....
cd $initial_dir
```
right after the `set -e` so that we're working in a guaranteed-fresh temporary directory.   We don't really need the `rm -rf` part at this point, since the directory will be cleaned up on a reboot and isn't terribly large to begin with.

**Comment by songweijia** [comment]
Using tmp file system is a good idea for moving this out of the derecho folder. However, libfabric building is pretty large. And according to [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard),  `/tmp` is "often not preserved between system reboots, and may be severely size restricted."  I recommend using `/var/tmp` for "Temporary files to be preserved between reboots." The user can delete the build folder later on.

**Comment by mpmilano** [comment]
It looks like libfabrics might actually be packaged at an adequate version for us.  If we can depend on the packaged version rather than a build of a specific hash, our users' lives (and our own lives) would much improve.  FWIW, "severely restricted" for `/tmp` is still at least 1GB on any user-facing system.  The gnome/KDE desktop environments appear to assume this.

**Comment by etremel** [comment]
Is this issue resolved now? I think Weijia fixed the dangerous problems with the install scripts, and they're about to become obsolete anyway now that we have a package-based way to install Derecho dependencies.

**Comment by etremel** [comment]
Given the lack of response on this issue, I'm going to assume that it's fixed in our latest version.
