### ISSUE TITLE
Persistence thread can block forever during view change

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho#144]
While testing my changes to the view change logic in support of issue #126, I discovered a possibly long-standing bug in the way PersistenceManager updates the persisted_num columns in the SST. Since PersistenceManager uses its own thread, separate from the SST predicates thread, it's possible for the SST put that updates persisted_num (line 73) to execute concurrently with a failure detection (e.g. the "suspected changed" trigger) that marks a row as frozen. This means that the persistence thread can enter the SST::put(receiver_ranks, offset, size) function, see that the failed node's row is not yet frozen, and then attempt to post a remote write to the failed node even though it is now marked as frozen. The remote write to the failed node will then block forever; I'm not sure why exactly, but I think it's because one of the many macros invoked by resources::post_remote_write unpacks into a loop that continuously retries the RDMA one-sided write. As a result, the view change that removes the failed node will get stuck at the "waiting for persistence" phase, because the persistence thread never finished updating persisted_num on the non-failed nodes.

**Comment by etremel** [comment]
This might have been fixed by 790255ddc89e3bbe0ef25046b04ec7c51589beb0, since it's now possible for a post_remote_write to be aborted if another thread detects a failure and calls report_failure() on the resources object. It's hard to reproduce this deadlock so I can't be entirely sure, but I haven't seen it since integrating that commit.

**Comment by KenBirman** [comment]
No longer seen, v2.0 testing was pretty intensive.  Closed, but could reopen if anyone sees the problem again.
