### ISSUE TITLE
Performance issue with p2p_send

### ISSUE THREAD

**Issue by xinzheyang** [Derecho-Project/derecho#154]
When I was testing the performance for external client and trying to compare it with normal in-group `p2p_send`, I found the throughput for normal in-group `p2p_send` abnormally low.

timespan:10412.2 millisecond.
throughput:0.0786771Gbit/s.
throughput:960.414ops.

The test script I used is `applications/archive/external_client_perf_test.cpp` in `external_client` branch.

Possibly related to #49 ?

**Comment by xinzheyang** [comment]
Quote from Sagar's email:

> We found that p2p_latency_test, maintained by us for a long time, still gives decent numbers. The latency has increased only by a factor of 2, which is not surprising since we have refactored the code recently and haven't debugged performance for a long time. But our test is using P2P in a synchronous manner - each request is followed by a wait for the reply by a get() on the returned future object.
Xinzhe is doing a slightly different experiment. He initiates the 10000 calls asynchronously without tracking the replies and makes a final call in the end synchronously. His experiment results in a 50-100 fold increase in latency. This suggests that performance does not scale when a large number of replies have to be managed in the background.

**Comment by xinzheyang** [comment]
The issue was that in `p2p_receive_loop()` of `rpc_manager.cpp`, the thread `sleep`s for 1ms when it should not do so (because the thread is doing actual work, instead of inactive).

The new throughput for in-group `p2p_send`: (msg_size=10240, p2p_window_size=16)
timespan:2907.58 millisecond.
throughput:28.1747Gbit/s.
throughput:343929ops.

The new throughput for external client `p2p_send`:
timespan:2753.21 millisecond.
throughput:29.7543Gbit/s.
throughput:363212ops.

These numbers are in line with our expectation and external client achieves same performance as in-group p2p_send.

**Comment by songweijia** [comment]
Great! Is this fix included in a commit on the external_client branch?
