### ISSUE TITLE
Remove noexcept(false) annotations

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho#159]
According to everything I can find on the Internet (such as [this](https://stackoverflow.com/questions/16244313/does-adding-noexceptfalse-benefit-the-code-in-any-way) and [this](https://akrzemi1.wordpress.com/2014/04/24/noexcept-what-for/)), the `noexcept(false)` annotation on a function does nothing. Therefore, we should remove it from the Derecho codebase to reduce unnecessary "noise" in the source code and potential sources of confusion for other developers who use our library (they might wonder why some functions are declared `noexcept(false)` and some are not, until they figure out that not writing `noexcept(false)` is exactly the same as writing it).

**Comment by songweijia** [comment]
I agree to remove `noexcept(false)` since it does not take effect. I do think C++ should come with a non-parameterized `noexcept` syntax.

**Comment by etremel** [comment]
Oh, C++ does have a non-parameterized noexcept - if you just write `noexcept` on a function declaration (with no parentheses) it's exactly equivalent to writing `noexcept(true)`. If you want, I can also change all of our `noexcept(true)` to `noexcept`.

**Comment by songweijia** [comment]
I'm not sure if you noticed a compilation warning on in commit 4a402b6. Some functions in C++ are by default evaluated to `noexcept(false)`, for example, the destructors. And in such a case, `noexcept(false)` makes sense.
"""
non-throwing functions are all others (those with `noexcept` specifier whose expression evaluates to true as well as destructors, defaulted special member functions, and deallocation functions)
"""
Source [link](https://en.cppreference.com/w/cpp/language/noexcept_spec). So I reversed one of such a case in 3d6038f.

**Comment by etremel** [comment]
Oh, you're right. I didn't notice the compile warning because our build process produces so much output, but yes, a destructor is one case where declaring `noexcept(false)` actually has an effect.
