### ISSUE TITLE
[documentation] README.md contains broken link

### ISSUE THREAD

**Issue by brettsheffield** [Derecho-Project/derecho#161]
The paper referenced by the README returns a 404 not found error:
[http://www.cs.cornell.edu/ken/derecho-tocs.pdf](http://www.cs.cornell.edu/ken/derecho-tocs.pdf)

**Comment by KenBirman** [comment]
Brett, it looks like one of the Cornell web servers has crashed.  Thanks for bringing this to our attention... I’ve filed a ticket.

**Comment by KenBirman** [comment]
Brett, a copy of the paper you were trying to access is attached here, as a work-around until the Cornell server is repaired.

[derecho-tocs.pdf](https://github.com/Derecho-Project/derecho/files/4779966/derecho-tocs.pdf)

**Comment by brettsheffield** [comment]
Many thanks - looking forward to reading it.

**Comment by KenBirman** [comment]
I see that you are working on open networking stacks with an IPv6 layering.  Derecho is fully open, and doesn't require RDMA, so it makes sense to consider it.  The system definitely could run on an IPv6 network with some porting effort, but we haven't tried that at Cornell.
