### ISSUE TITLE
Support for atomics needed in the SST

### ISSUE THREAD

**Issue by KenBirman** [Derecho-Project/derecho#165]
The SST needs to support atomics, and will require some testing to confirm that any solution actually works.  It turns out that the RDMA atomics spec now forbids polling in a one-sided RDMA receiver unless you poll on a variable declared as atomic.  Then the one-sided push has to use an atomic flag to tell RDMA verbs that the transfer includes an object of atomic type.  (They also now have a selective memory fence feature, by the way, so you can turn fencing on or off, verb by verb). 

This atomics specification is somewhat new, apparently, and not really enforced in current Intel memories with current Mellanox RDMA.  But eventually, of course, it will be enforced.  Additionally, we don't know when LibFabrics will pass these options through, but this all adds up to a risk that on some unknown future date, SST guards (which are used as atomics on which we poll) would break, causing all of Derecho and Cascade to become buggy.

Attached is some relevant information from Mark Silberstein at Technion.
[Atomics in RDMA.pdf](https://github.com/Derecho-Project/derecho/files/4858233/Atomics.in.RDMA.pdf)

**Comment by songweijia** [comment]
Both ibverbs and libfabric API supported this atomic feature. We just need to set a flag (`ibv_send_wr.send_flags|=IBV_SEND_FENCE` for ibverbs API and `flags|FI_FENCE`). Let's try this with Kwang's example to see if it fixes.
