### ISSUE TITLE
mutils-serialization's support for std::tuple is broken

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho#170]
The mutils-serialization library that is bundled with Derecho includes built-in support for serializing some standard library types, including `std::vector` and `std::tuple`. However, attempting to serialize a `std::tuple` containing a `std::vector` does not actually work as expected. For a minimal, reproducible example, try compiling this program:
```
#include <tuple>
#include <vector>

#include <derecho/mutils-serialization/SerializationSupport.hpp>

class TupleTest : public mutils::ByteRepresentable {
    std::tuple<int32_t, int64_t, std::vector<uint32_t>> tuple_with_vector;

public:
    TupleTest() : tuple_with_vector{-1, -1, {0, 0, 0}} {};
    TupleTest(const std::tuple<int32_t, int64_t, std::vector<uint32_t>>& t) : tuple_with_vector(t){};
    DEFAULT_SERIALIZATION_SUPPORT(TupleTest, tuple_with_vector);
};

int main(int argc, char** argv) {
    TupleTest a_test;
}
```
The compiler will spew a page full of errors that indicate, eventually, that it couldn't find a `post_object` function that matches an argument of type `std::vector<unsigned int>`. Puzzlingly, SerializationSupport.hpp includes exactly the function it's looking for on line 511: `void post_object(const std::function<void(char const* const, std::size_t)>& f, const std::vector<T>& vec)`.

The problem appears to be that SerializationSupport.hpp declares the post_object function for std::tuple on line 498, right *before* the declaration of post_object for std::vector. This means when the compiler is doing template expansion on this function, it hasn't yet seen the declaration of post_object for std::vector and thinks it doesn't exist. If I cut and paste the definition of post_object for tuples to appear *after* the declaration of post_object for vectors, the same program compiles without error.

Assuming that this simple cut-and-paste is the correct solution, though, I'm still not sure exactly where to commit the change. The mutils-serialization library actually appears in two different places in our repository system: once as a subdirectory of the derecho repository, and once as its own repository at https://github.com/Derecho-Project/mutils-serialization, which is in turn forked from (and divergent from) Matthew's original repository at https://github.com/mpmilano/mutils-serialization. Also, the version that's a subdirectory within the derecho repository is not equal to the version in our forked repository -- they have different commit histories, and the subdirectory version is missing some changes that appear in the forked-repository version.

This means there are two questions to resolve here:
1. Is my understanding of, and fix for, this bug correct?
2. Which version of mutils-serialization should I make the fix in?

**Comment by songweijia** [comment]
A similar appeared before. I'm wondering if we should move all of the `post_object` function declarations in a section before we define them. We want both object types work: `std::vector<std::tuple>` and `std::tuple<...,std::vector<>,...>`.

For the repo, let's post it to the mutils-serialization in derecho source tree, which is different from the original one in Matthew's repo.

**Comment by mpmilano** [comment]
yes, everything in that file should be forward-declared and not everything is. Sorry folks.

**Comment by etremel** [comment]
I just realized this issue wasn't auto-closed by my commit because GitHub's parser doesn't know the phrase "fixes the bug." Closing it now.
