### ISSUE TITLE
RDMC send does not need to wait for persistence thread.

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#176]
Aahil and Peter evaluated the performance of `typed_subgroup_bw_test` with persistence enabled. They found that SMC is many times faster than RDMC with the same message size and window size settings. I verified it using 10KB messages.

After digging into the code, I found that RDMC sending thread (defined in `derecho::MulticastGroup::send_loop()`) will stop to wait if the difference between the latest persisted message and the message to send reaches the preconfigured window size. The code is at [here](https://github.com/Derecho-Project/derecho/blob/70e37f57ebcd63bef844e8fbff686d42c3e95ff1/src/core/multicast_group.cpp#L1012). Actually, it's only necessary to wait when the difference between the latest delivered message and the message to send reaches the window size, because the send buffers are used up.

My suggestion is to the issue is eliminating the second condition at line 1012. @sagarjha could you have a look at this?

**Comment by sagarjha** [comment]
I can fix this issue in master now.

**Comment by sagarjha** [comment]
@songweijia Note that we will be having the same performance worries once we implement write-ahead logging as outlined in issue #74.

**Comment by songweijia** [comment]
@sagarjha Thank you for this fix. Yes, I know that once implementing the write-ahead log in #74, this issue will come back. Ken mentioned possible approaches: batching small messages in RDMC like what you do with SST multicast. That will help improve the persistence performance without flushing every RDMC. We can keep this in mind when we adding support for #74.
