### ISSUE TITLE
Possible compilation issue with SST

### ISSUE THREAD

**Issue by KenBirman** [Derecho-Project/derecho#208]
Andrew Appel is an expert on C and C++ compilation, and warns that our SST design may need a very small change to correctly signal to the compiler that we do I/O from the SST memory area.

As he explains it, the C compiler (in the current ANSI standard and beyond) expects that any memory on which I/O will occur is annotated as "atomic".  This ensures that when an I/O operation occurs, such as a one-sided RDMA write, the prior writes to SST memory will be visible to the sender-side NIC.  Andrew argues that lacking this annotation, the compiler is free to generate code that (for example) holds the written value in a register, or on the stack, or simply removes the write because it deduces that no read of that location will occur.

I am unsure how easy or hard this will be to implement.  SST writes to a cell work by computing the location of that cell, then casting the pointer to point to the proper type of object (the "decltype" of the cell), and then doing a dereferenced store.  If this kind of cast can simply designate that the type is the proper flavor of atomic, we would be done on the sender side (and the same approach would then also be used on the receiver side).  But I have a vague memory that you cannot cast to an atomic type.  Research on this question is needed.

**Comment by mpmilano** [comment]
Hi Ken, 

We're actually using a similar C++ feature right now to achieve this -- the annotation of "volatile", which was actually designed with DMA or memory-mapped IO applications in mind. If you look at the Microsoft implementation of atomics on Intel, you'll see that it's actually implemented as a simple wrapper that holds a volatile field, and doesn't need to do anything else. 

Note that this is actually X86-TSO specific; we would probably need to figure out the appropriate flush barriers for Derecho on NUMA or Arm.

**Comment by KenBirman** [comment]
Interesting that you mention ARM – Andrew specifically said that ARM is where we might encounter the issue.  But if SST objects are declared as volatile, then I agree that this should be signaling our intentions to the compiler.

By the way, Andrew also expressed concern that gcc and clang might not be identical in their handling of these annotations.

**Comment by mpmilano** [comment]
GCC and Clang both emit the same instructions for volatile load and store, but MSVCC does something weird instead -- it has a compiler switch which toggles between "Microsoft standard" and "c++ standard", with Microsoft standard granting even more guarantees + sequential consistency

**Comment by KenBirman** [comment]
I agree, casting to volatile will ensure correct behavior in this case.
