### ISSUE TITLE
Question about "append instead of overwrite"

### ISSUE THREAD

**Issue by Steamgjk** [Derecho-Project/derecho#232]
I am playing with simple_replicated_objects_json
I notice that for the Foo part, every time a node ordered_send an update, it overwrites the value of Foo. 

Here I want the value of Foo to be something like a log list/vector, e.g. every time a node _ordered_send_ a request, this request is appended in the Foo vector, and derecho guarantees consistent log sequence across all nodes. How can I do this? Any pointers to the example code?  Thanks.

**Comment by KenBirman** [comment]
Well, you just have to configure the group in persistent mode (not volatile mode).  Now each new value is saved (logged) as a distinct new version.  Later you can fetch the versions by version number, by specifying the version you wish to retrieve when you call get.

**Comment by KenBirman** [comment]
PS: Issues are bugs.  This belongs in "discussions"
