### ISSUE TITLE
Actually disable debugging in release mode

### ISSUE THREAD

**Issue by mpmilano** [Derecho-Project/derecho#39]
the CMakeLists.txt file explicitly overrides CMake's DEBUG flags, and drops the one that actually disables debugging-mode (NDEBUG on Linux).  So we're running with all asserts, and a boatload of debugging-only code, enabled. Even in release.  

We should fix that.  This might have something to do with issue #33 too, or at least it'll provide a handy way to disable spdlog.

**Comment by mpmilano** [comment]
This will be an 'ongoing effort' sort of deal; we need to make sure all asserts can be safely disabled without changing user-facing behaviour.

**Comment by mpmilano** [comment]
SPDLog has a level switch - we should hook this up to the underlying "debugging disable" switch.

**Comment by songweijia** [comment]
We did this already, right?

**Comment by sagarjha** [comment]
Part of it is done.
What remains is making sure we have some checks in place in the Release mode for user mistakes. We want asserts to check for developer bugs only.

**Comment by KenBirman** [comment]
This was resolved in the v2.0 release
