### ISSUE TITLE
libfabric not working with Ubuntu 18.04.1 LTS in Amazon EC2

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#48]
I tried the master commit 28702214b65fb2fc1de1638c010ce8f1d9beca12 on two amazon instances with ubuntu 18 (John is trying to run Derecho on that setup.):

lsb-release: 18.04.1 LTS
uname -a: Linux ip-172-31-4-174 4.15.0-1019-aws #19-Ubuntu SMP Fri Aug 10 09:34:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)  
ami-id:ami-05fb04e2687120d6b
az:us-east-1a
instance-type:c5.2xlarge

The issue is that libfabric reports a system interruption on initialization. Then it stopped on fi_endpoint call in lf.cpp:242 with error number 22(invalid argument). 

I haven't tried this with other ubuntu 18 setup. Need further investigation.

**Comment by KenBirman** [comment]
Closed -- Edward tracked the issue to Ubuntu's package download system using an old version of libfabrics.  Our install script now explicitly uses a more recent version.
