### ISSUE TITLE
P2P send Latency issue

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho#49]
Weijia and I have noticed that the P2P latency for the first message send is unapologetically high with libfabric verbs. We should find the reason for this. We should also investigate if this issue shows up in other kind of messages.

**Comment by KenBirman** [comment]
Maybe slow-start hasn’t been disabled?  For our work, we wouldn’t want it...

On Sep 13, 2018, at 9:58 PM, Sagar Jha <notifications@github.com<mailto:notifications@github.com>> wrote:


Weijia and I have noticed that the P2P latency for the first message send is unapologetically high with libfabric verbs. We should find the reason for this. We should also investigate if this issue shows up in other kind of messages.

**Comment by KenBirman** [comment]
This is apparently a manifestation of #160
