### ISSUE TITLE
Derecho_bw_test performance issue

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#50]
After 1) using separate operations for data and counter in SST and 2) upgrade to latest libfabric(commit:d133dd39ee23eb625b413c87f617a2e45558e12a). It is good to see that 10KB message atomic broadcast throughput does not hurt, even with an extra SST put for the sequence number. However, throughput dropped a little bit for 1MB and 100MB messages. Maybe we need more data points.... to be verified and investigated.
**derecho_bw_test** performance: 

- with old libfabric + 1 SST for both data and seq:
2 0 10000 30 1000000 0 2.89461
2 0 1000000 15 10000 0 8.52146
2 0 100000000 5 200 0 15.0009
2 0 10000 30 1000000 0 2.89957
2 0 1000000 15 10000 0 8.5105
2 0 100000000 5 200 0 14.9067
2 0 10000 30 1000000 0 2.94421
2 0 1000000 15 10000 0 8.43879
2 0 100000000 5 200 0 15.2114
2 0 10000 30 1000000 0 2.85426
2 0 1000000 15 10000 0 8.57302
2 0 100000000 5 200 0 15.1146
2 0 10000 30 1000000 0 2.9251
2 0 1000000 15 10000 0 8.5739
2 0 100000000 5 200 0 14.9813

- with new libfabric + 1 SST for data and 1 SST for seq:
2 0 1000000 15 10000 0 7.55985
2 0 1000000 15 10000 0 7.70658
2 0 10000 30 100000 0 2.84406
2 0 10000 30 1000000 0 3.11125
2 0 100000000 5 200 0 14.8722
2 0 100000000 5 200 0 14.5425

**Comment by KenBirman** [comment]
Closed by Lorenzo Rosa's work on performance.
