### ISSUE TITLE
Print the Version message on Derecho starting and in fatal error messages.

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#94]
As we have more users, it would be helpful to solve the issues if we print the version message on starting Derecho and fatal error. [Here](https://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable) is one example to realize this feature.

**Comment by etremel** [comment]
This will be easy to do once I implement #90, since that also requires injecting the current Derecho version into the source code as a constant.
