### ISSUE TITLE
High latency for Derecho atomic multicast

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho#98]
The latency of atomic multicast, as measured on the Fractus nodes is unreasonably high (4-10 times). I am pretty sure that this is result of some refactoring from solving issue #78 that causes locks to be held over coarser regions/longer periods of time that cause contention. 
Since, we are refactoring sends as per issue #70, I will fix this issue when I work on that one (pretty soon, in other words).

**Comment by KenBirman** [comment]
Closed, addressed by V2.0 bug fixes and then definitively resolved by Lorenzo Rosa's research, which will find its way into V2.1
